### PR TITLE
Wagtail 2.0b1 compatibility

### PR DESCRIPTION
**Pull request by rspeed**
The first beta of Wagtail 2 has some backwards-incompatible changes from version 1. Specifically, it removes the redundancy in page names (ex: `wagtail.wagtailcore` => `wagtail.core`) and bumps its Django requirement to version 2.

Unfortunately, this PR also breaks compatibility with Wagtail 1, so it's more of a stopgap solution for testing the beta. Maintaining compatibility will require quite a bit more work.

### CODE REVIEW

**Comment by robvdl** [comment]
Shouldn't you also remove py27 from the travis yaml file, neither Wagtail 2, nor Django 2 support Python 2.7 anymore.

**Comment by JamesRamm** [comment]
Thanks for this PR
Before merging I have a couple of tasks to do:
#146
#145
 but then this will be next on the list.

**Comment by rspeed** [comment]
I'll fix the merge conflicts.

**Comment by JamesRamm** [comment]
I've merged this into the branch longclaw2.0 and will continue work there

**Pull request closed without merging**
