### PR TITLE
CSS changes to order detail view #38

### PR DESCRIPTION
**Pull request by alexfromvl**
Changed the feature class and added an padding for UNFULFILLED and FULFILLED

### CODE REVIEW

**Comment by JamesRamm** [comment]
Hi
Thanks for this.
There are a couple of problems which will prevent it from being merged:

1. If we use the 'button' class then the fulfilled/unfulfilled label becomes 'clickable', although it does nothing, which is a bit confusing. 

2. In React, we cannot pass a `style` string to a component anymore; it throws this error:

```
The `style` prop expects a mapping from style properties to values, not a string. For example, style={{marginRight: spacing + 'em'}} when using JSX. This DOM node was rendered by `OrderDetail`
```

**Comment by alexfromvl** [comment]
Hi.
Tried several different options from the original file - core.css.
I chose the 'button' class as the optimal one - maybe it's worth to add a link to it so that when I click it, I go to the page with orders with the filter "By status - Fulfilled" turned on.
As for the `style` in React understood, I'll think about another solution.

**Comment by JamesRamm** [comment]
@alexfromvl 
Just so you know, Im not ignoring this - just quite busy atm and trying to think of a solution for the `button` class...

**Comment by alexfromvl** [comment]
@JamesRamm 
What do you think if you just apply a pure `style` for a given element with the desired values?

Example:
```
const spanStyle = {
      padding: '8px';
      color: '#fff';
      background-color: '#e9b04d';
      border: '1px solid #e9b04d';
};

<span className="help help-warning" style={spanStyle}>
              UNFULFILLED&nbsp;
                    </span>
```

**Comment by JamesRamm** [comment]
@alexfromvl yes that would be ideal

**Comment by alexfromvl** [comment]
@JamesRamm  Updated the code. Checked on the local version, everything worked

**Pull request merged**
